import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   
};

export default sidebars;*/

const sidebars: SidebarsConfig = {
  // 1. 철학 섹션을 위한 사이드바
  philosophySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // philosophy 폴더 내부의 모든 문서를 자동으로 구성
    },
  ],

  // 2. 컴퓨터 공학 섹션을 위한 사이드바
  computerSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // computer 폴더 내부의 모든 문서를 자동으로 구성
    },
  ],
};

export default sidebars;